In [42]:
# Given Data

import numpy as np
import cvxpy as cp
from scipy import linalg

np. random.seed (0)

n = 5 # dimension
N = 100 # number of distance samples
N_test = 10

X = np. random.normal(size =(n, N))
Y = np. random.normal(size =(n, N))

P = np.random.normal (size =(n, n))
P = P @ P.T + np.eye(n)
sqrtP = linalg.sqrtm (P)

d = np.linalg.norm (sqrtP @ (X - Y), axis =0) # exact distances
d = np.maximum(np.zeros (len(d)), d+np.random.normal( size =(1 , N))) # add noise and make nonnegative

# create sets to determine if X and Y are similar to each other
distances = np.linalg.norm(X - Y, axis=0)

# for similarity
threshold = 1.0  

similar_set = np.where(distances <= threshold)[0]
not_similar_set = np.where(distances > threshold)[0]






In [47]:
import numpy as np
import cvxpy as cp

# problem 5

# Given data
n = 5  # dimension
N = 100  # number of distance samples
N_test = 10

X = np.random.normal(size=(n, N))
Y = np.random.normal(size=(n, N))

# Constructing the distance matrix
P = np.random.normal(size=(n, n))
P = P @ P.T + np.eye(n)
sqrtP = np.linalg.cholesky(P)
distances = np.linalg.norm(sqrtP @ (X - Y), axis=0)
d_true = np.maximum(np.zeros(len(distances)), distances + np.random.normal(size=(1, N)))

# Sets for similarity and dissimilarity
similar_set = np.where(distances <= threshold)[0]
not_similar_set = np.where(distances > threshold)[0]

# Convex optimization problem
A = cp.Variable((n, n), symmetric=True)  # Positive semi-definite matrix
d_predicted = M @ (X - Y)


squared_error = cp.sum_squares(d_predicted - d_true)

prob = cp.Problem(cp.Minimize(squared_error))
prob.solve()


if prob.status == cp.OPTIMAL:
    # Optimal matrix M
    optimal_A = A.value
    print("Optimal A:\n", optimal_M)
else:
    print("Problem was not solved successfully.")



Optimal A:
 [[ 0.28332619  0.10190303  0.2609798   0.08383585 -0.08832993]
 [ 0.10190303 -0.06346669  0.07605456 -0.10060897 -0.23740941]
 [ 0.2609798   0.07605456  0.23565457  0.05064444 -0.11861157]
 [ 0.08383585 -0.10060897  0.05064444 -0.14886147 -0.29827173]
 [-0.08832993 -0.23740941 -0.11861157 -0.29827173 -0.39423258]]
